server:
  port: 3309                   # ?????
  servlet:
    context-path: /api         # ???????
  error:
    include-message: always    # ????????

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.29.181.103:3308/esystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true  # ????? URL
    username: root
    password: 20030416cjh
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update         # ??????????
    show-sql: true              # ???? SQL ??

logging:
  level:
    root: info                # ????            # ????

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
